/* eslint-disable */
// AUTOGENERATED by `pnpm audit-defaults`. Do not edit by hand.
//
// Each entry was proven by rendering the component twice — once with the
// prop, once without — and comparing markup and tasty CSS. See
// `src/eslint-plugin/probe.tsx`.

import { DefaultsRegistry } from './types';

export const DEFAULTS: DefaultsRegistry = {
  components: {
    Alert: {
      props: {
        display: { kind: 'default', value: 'block' },
        flow: { kind: 'default', value: 'column' },
        preset: { kind: 'default', value: 't3' },
        shape: { kind: 'default', value: 'card' },
        theme: { kind: 'default', value: 'note' },
      },
    },
    AlertDialog: {
      props: {
        isDismissable: { kind: 'default', value: false },
      },
    },
    Avatar: {
      props: {
        display: { kind: 'default', value: 'grid' },
        fontWeight: { kind: 'default', value: 500 },
        placeContent: { kind: 'default', value: 'center' },
        radius: { kind: 'default', value: 'round' },
        size: { kind: 'default', value: '4x' },
      },
    },
    Badge: {
      props: {
        autoHideActions: { kind: 'default', value: false },
        disableActionsFocus: { kind: 'default', value: false },
        highlightCaseSensitive: { kind: 'default', value: false },
        isLoading: { kind: 'default', value: false },
        isSelected: {
          kind: 'skip',
          reason: 'reflected-attribute',
          note: 'Reflected as `aria-selected={isSelected}`, so omitting the prop removes the attribute while `false` emits `aria-selected="false"`. Not safe to strip.',
        },
        level: { kind: 'default', value: 3 },
        preserveActionsSpace: { kind: 'default', value: false },
        size: { kind: 'default', value: 'inline' },
        theme: { kind: 'default', value: 'special' },
        tooltip: { kind: 'default', value: true },
      },
    },
    Banner: {
      props: {
        autoHideActions: { kind: 'default', value: false },
        disableActionsFocus: { kind: 'default', value: false },
        highlightCaseSensitive: { kind: 'default', value: false },
        isDismissable: { kind: 'default', value: false },
        isSelected: {
          kind: 'skip',
          reason: 'reflected-attribute',
          note: 'Reflected as `aria-selected={isSelected}`, so omitting the prop removes the attribute while `false` emits `aria-selected="false"`. Not safe to strip.',
        },
        level: { kind: 'default', value: 3 },
        preserveActionsSpace: { kind: 'default', value: false },
        shape: { kind: 'default', value: 'button' },
        theme: { kind: 'default', value: 'note' },
      },
    },
    Board: {
      props: {
        allowOverlap: { kind: 'default', value: false },
        collisionMode: { kind: 'default', value: 'revert' },
        cols: { kind: 'default', value: 12 },
        compact: { kind: 'default', value: 'vertical' },
        extraRows: { kind: 'default', value: 0 },
        isAligned: { kind: 'default', value: false },
        isAutoHeight: { kind: 'default', value: false },
        isCard: { kind: 'default', value: false },
        isDraggable: { kind: 'default', value: true },
        isDroppable: { kind: 'default', value: true },
        isResizable: { kind: 'default', value: true },
        maxRows: { kind: 'default', value: 'Infinity' },
        preventCollision: { kind: 'default', value: false },
        resizeGripPlacement: { kind: 'default', value: 'inside' },
        rowHeight: { kind: 'default', value: 100 },
        selectionCancel: { kind: 'default', value: 'BOARD_SELECTION_CANCEL' },
        selectionMode: { kind: 'default', value: 'none' },
        showGridLines: { kind: 'default', value: false },
      },
    },
    Button: {
      props: {
        defaultTooltipPlacement: { kind: 'default', value: 'top' },
        isLoading: { kind: 'default', value: false },
        isSelected: { kind: 'default', value: false },
        size: {
          kind: 'skip',
          reason: 'conditional',
          note: 'Redundant in a bare tree but load-bearing under "type="link"", so removing it would change behaviour there.',
        },
        theme: { kind: 'default', value: 'default' },
        type: { kind: 'default', value: 'outline' },
      },
    },
    ButtonSplit: {
      props: {
        isDisabled: { kind: 'default', value: false },
        size: { kind: 'default', value: 'medium' },
        theme: { kind: 'default', value: 'default' },
        type: { kind: 'default', value: 'outline' },
      },
    },
    Checkbox: {
      props: {
        defaultSelected: { kind: 'default', value: false },
        isIndeterminate: { kind: 'default', value: false },
        isSelected: { kind: 'default', value: false },
      },
    },
    ComboBox: {
      props: {
        allowsCustomValue: { kind: 'default', value: false },
        clearOnBlur: { kind: 'default', value: false },
        containerPadding: { kind: 'default', value: 8 },
        direction: { kind: 'default', value: 'bottom' },
        hideTrigger: { kind: 'default', value: false },
        isClearable: { kind: 'default', value: false },
        overlayOffset: { kind: 'default', value: 8 },
        popoverTrigger: { kind: 'default', value: 'input' },
        shouldCommitOnBlur: { kind: 'default', value: true },
        shouldFlip: { kind: 'default', value: true },
        size: { kind: 'default', value: 'medium' },
        suffixPosition: { kind: 'default', value: 'before' },
      },
    },
    CommandMenu: {
      props: {
        autoFocus: { kind: 'default', value: true },
        emptyLabel: { kind: 'default', value: 'No commands found' },
        isLoading: { kind: 'default', value: false },
        searchPlaceholder: { kind: 'default', value: 'Search commands...' },
        selectionMode: { kind: 'default', value: 'none' },
        shouldFilter: { kind: 'default', value: true },
        size: { kind: 'default', value: 'medium' },
      },
    },
    CommandTextArea: {
      props: {
        autoSize: { kind: 'default', value: false },
        containerPadding: { kind: 'default', value: 8 },
        direction: { kind: 'default', value: 'top' },
        insertSpaceAfter: { kind: 'default', value: true },
        maxRows: { kind: 'default', value: 10 },
        overlayOffset: { kind: 'default', value: 8 },
        rows: { kind: 'default', value: 3 },
        shouldFlip: { kind: 'default', value: true },
      },
    },
    CopyPasteBlock: {
      props: {
        radius: { kind: 'default', value: '1r' },
        size: { kind: 'default', value: 'medium' },
      },
    },
    CopySnippet: {
      props: {
        border: { kind: 'default', value: 0 },
        language: { kind: 'default', value: 'javascript' },
        padding: { kind: 'default', value: 0 },
        prefix: { kind: 'default', value: '' },
        radius: { kind: 'default', value: '1r' },
        showTooltip: { kind: 'default', value: false },
        title: { kind: 'default', value: 'Code example' },
      },
    },
    DataTable: {
      props: {
        autoHidePagination: { kind: 'default', value: true },
        cellSelectionMode: { kind: 'default', value: 'range' },
        columnContextMenu: { kind: 'default', value: true },
        defaultPageSize: { kind: 'default', value: 100 },
        isColumnReorderable: { kind: 'default', value: false },
        isHeaderSticky: { kind: 'default', value: true },
        isResizable: { kind: 'default', value: true },
        isRowMoveAnimated: { kind: 'default', value: true },
        isStriped: { kind: 'default', value: true },
        isVirtualized: { kind: 'default', value: 'auto' },
        loadingIndicator: { kind: 'default', value: 'overlay' },
        paginationMode: { kind: 'default', value: 'client' },
        rowKey: { kind: 'default', value: 'id' },
        shape: { kind: 'default', value: 'plain' },
        showRowNumbers: { kind: 'default', value: false },
        size: { kind: 'default', value: 'small' },
        skeletonRowCount: { kind: 'default', value: 6 },
      },
    },
    DatePicker: {
      props: {
        granularity: { kind: 'default', value: 'day' },
        hideTimeZone: { kind: 'default', value: true },
        hourCycle: { kind: 'default', value: 24 },
        maxVisibleMonths: { kind: 'default', value: 1 },
        shouldFlip: { kind: 'default', value: true },
        shouldForceLeadingZeros: { kind: 'default', value: true },
        size: { kind: 'default', value: 'medium' },
      },
    },
    Dialog: {
      props: {
        isDismissable: {
          kind: 'skip',
          reason: 'context',
          note: 'Redundant in a bare tree but load-bearing under "inside <DialogContext isDismissable>", so removing it would change behaviour there.',
        },
        role: { kind: 'default', value: 'dialog' },
        size: { kind: 'default', value: 'M', aliases: ['medium'] },
      },
    },
    DialogContainer: {
      props: {
        hideOnClose: { kind: 'default', value: false },
        isDismissable: { kind: 'default', value: true },
        isKeyboardDismissDisabled: { kind: 'default', value: false },
        type: { kind: 'default', value: 'modal' },
      },
    },
    DialogForm: {
      props: {
        preserve: { kind: 'default', value: false },
      },
    },
    DialogTrigger: {
      props: {
        containerPadding: { kind: 'default', value: 12 },
        crossOffset: { kind: 'default', value: 0 },
        hideArrow: { kind: 'default', value: false },
        isDismissable: { kind: 'default', value: true },
        isKeyboardDismissDisabled: { kind: 'default', value: false },
        mobileViewport: { kind: 'default', value: 700 },
        offset: { kind: 'default', value: 8 },
        shouldFlip: { kind: 'default', value: true },
        shouldRestoreFocus: { kind: 'default', value: true },
        type: { kind: 'default', value: 'modal' },
      },
    },
    Disclosure: {
      props: {
        defaultExpanded: { kind: 'default', value: false },
        isDisabled: { kind: 'default', value: false },
        shape: { kind: 'default', value: 'default' },
      },
    },
    DisplayTransition: {
      props: {
        animateOnMount: { kind: 'default', value: true },
        exposeUnmounted: { kind: 'default', value: false },
        preserveContent: { kind: 'default', value: true },
        respectReducedMotion: { kind: 'default', value: true },
      },
    },
    FileInput: {
      props: {
        size: { kind: 'default', value: 'default' },
        type: { kind: 'default', value: 'file' },
      },
    },
    FilterListBox: {
      props: {
        allowsCustomValue: { kind: 'default', value: false },
        disallowEmptySelection: { kind: 'default', value: false },
        isCheckable: { kind: 'default', value: false },
        isLoading: { kind: 'default', value: false },
        isLoadingItems: { kind: 'default', value: false },
        selectAllLabel: { kind: 'default', value: 'All' },
        selectionMode: { kind: 'default', value: 'single' },
        shouldFocusWrap: { kind: 'default', value: false },
        showSelectAll: { kind: 'default', value: false },
        size: { kind: 'default', value: 'medium' },
      },
    },
    FilterPicker: {
      props: {
        allowsCustomValue: { kind: 'default', value: false },
        containerPadding: { kind: 'default', value: 8 },
        disallowEmptySelection: { kind: 'default', value: false },
        htmlType: { kind: 'default', value: 'button' },
        isCheckable: { kind: 'default', value: false },
        isClearable: { kind: 'default', value: false },
        isLoadingItems: { kind: 'default', value: false },
        isReorderable: { kind: 'default', value: false },
        selectAllLabel: { kind: 'default', value: 'All' },
        selectionMode: { kind: 'default', value: 'single' },
        shouldFlip: { kind: 'default', value: true },
        shouldFocusWrap: { kind: 'default', value: false },
        showSelectAll: { kind: 'default', value: false },
        size: { kind: 'default', value: 'medium' },
        theme: { kind: 'default', value: 'default' },
        type: { kind: 'default', value: 'outline' },
      },
    },
    Form: {
      props: {
        isReadOnly: { kind: 'default', value: false },
        labelPosition: { kind: 'default', value: 'top' },
        necessityIndicator: { kind: 'default', value: 'icon' },
        orientation: { kind: 'default', value: 'vertical' },
        requiredMark: { kind: 'default', value: true },
        showValid: { kind: 'default', value: false },
        validateTrigger: { kind: 'default', value: 'onBlur' },
      },
    },
    GridProvider: {
      props: {
        columns: { kind: 'default', value: 2 },
        display: { kind: 'default', value: 'contents' },
        gap: { kind: 'default', value: '0' },
      },
    },
    HotKeys: {
      props: {
        type: {
          kind: 'skip',
          reason: 'reflected-attribute',
          note: 'Rendered as `data-type={type}` with no default, so omitting the prop drops the attribute while "default" emits it.',
        },
      },
    },
    HueSlider: {
      props: {
        labelPosition: { kind: 'default', value: 'top' },
        orientation: { kind: 'default', value: 'horizontal' },
        showValueLabel: { kind: 'default', value: true },
      },
    },
    InfoBadge: {
      props: {
        size: { kind: 'default', value: 'medium' },
        theme: { kind: 'default', value: 'default' },
        type: { kind: 'default', value: 'clear' },
      },
    },
    InlineInput: {
      props: {
        allowEmpty: { kind: 'default', value: false },
        defaultIsEditing: { kind: 'default', value: false },
        editTrigger: { kind: 'default', value: 'dblclick' },
        isDisabled: { kind: 'default', value: false },
        isReadOnly: { kind: 'default', value: false },
        isStyled: { kind: 'default', value: false },
        keyboardActivation: { kind: 'default', value: true },
        submitOnBlur: { kind: 'default', value: true },
        tooltip: { kind: 'default', value: true },
        tooltipPlacement: { kind: 'default', value: 'top' },
        trimOnSubmit: { kind: 'default', value: true },
      },
    },
    Item: {
      props: {
        autoHideActions: { kind: 'default', value: false },
        descriptionPlacement: { kind: 'default', value: 'inline' },
        disableActionsFocus: { kind: 'default', value: true },
        highlightCaseSensitive: { kind: 'default', value: false },
        isLoading: { kind: 'default', value: false },
        isSelected: {
          kind: 'skip',
          reason: 'reflected-attribute',
          note: 'Reflected as `aria-selected={isSelected}`, so omitting the prop removes the attribute while `false` emits `aria-selected="false"`. Not safe to strip.',
        },
        level: { kind: 'default', value: 3 },
        loadingSlot: { kind: 'default', value: 'auto' },
        preserveActionsSpace: { kind: 'default', value: false },
        shape: {
          kind: 'skip',
          reason: 'conditional',
          note: 'Redundant in a bare tree but load-bearing under "type="card"", so removing it would change behaviour there.',
        },
        size: { kind: 'default', value: 'medium' },
        theme: { kind: 'default', value: 'default' },
        tooltip: { kind: 'default', value: true },
        type: { kind: 'default', value: 'item' },
      },
    },
    ItemAction: {
      props: {
        isDisabled: {
          kind: 'skip',
          reason: 'context',
          note: 'Redundant in a bare tree but load-bearing under "inside <ItemActionProvider isDisabled>", so removing it would change behaviour there.',
        },
        isLoading: { kind: 'default', value: false },
        isSelected: { kind: 'default', value: false },
        theme: { kind: 'default', value: 'current' },
        type: { kind: 'default', value: 'clear' },
      },
    },
    ItemBadge: {
      props: {
        isLoading: { kind: 'default', value: false },
        isSelected: {
          kind: 'skip',
          reason: 'reflected-attribute',
          note: 'Reflected as `aria-selected={isSelected}`, so omitting the prop removes the attribute while `false` emits `aria-selected="false"`. Not safe to strip.',
        },
        theme: { kind: 'default', value: 'current' },
        type: { kind: 'default', value: 'clear' },
      },
    },
    ItemButton: {
      props: {
        disableActionsFocus: { kind: 'default', value: false },
        highlightCaseSensitive: { kind: 'default', value: false },
        level: { kind: 'default', value: 3 },
        preserveActionsSpace: { kind: 'default', value: false },
        shape: { kind: 'default', value: 'button' },
        size: { kind: 'default', value: 'medium' },
      },
    },
    ItemCard: {
      props: {
        autoHideActions: { kind: 'default', value: false },
        disableActionsFocus: { kind: 'default', value: false },
        highlightCaseSensitive: { kind: 'default', value: false },
        isLoading: { kind: 'default', value: false },
        isSelected: {
          kind: 'skip',
          reason: 'reflected-attribute',
          note: 'Reflected as `aria-selected={isSelected}`, so omitting the prop removes the attribute while `false` emits `aria-selected="false"`. Not safe to strip.',
        },
        level: { kind: 'default', value: 3 },
        preserveActionsSpace: { kind: 'default', value: false },
        size: { kind: 'default', value: 'medium' },
        tooltip: { kind: 'default', value: true },
      },
    },
    ItemTable: {
      props: {
        autoHidePagination: { kind: 'default', value: true },
        bulkBarPlacement: { kind: 'default', value: 'floating' },
        columnContextMenu: { kind: 'default', value: true },
        defaultPage: { kind: 'default', value: 1 },
        defaultPageSize: { kind: 'default', value: 50 },
        headerPreset: { kind: 'default', value: 'c3' },
        isHeaderHidden: { kind: 'default', value: false },
        isHeaderSticky: { kind: 'default', value: true },
        isLoading: { kind: 'default', value: false },
        isReorderable: { kind: 'default', value: false },
        isResizable: { kind: 'default', value: false },
        isRowMoveAnimated: { kind: 'default', value: true },
        isSearchable: { kind: 'default', value: false },
        isStriped: { kind: 'default', value: false },
        isVirtualized: { kind: 'default', value: 'auto' },
        loadingIndicator: { kind: 'default', value: 'overlay' },
        overscan: { kind: 'default', value: 12 },
        paginationMode: { kind: 'default', value: 'client' },
        rowContextMenu: { kind: 'default', value: false },
        rowKey: { kind: 'default', value: 'id' },
        searchDelay: { kind: 'default', value: 500 },
        searchMode: { kind: 'default', value: 'client' },
        selectAllMode: { kind: 'default', value: 'page' },
        selectionMode: { kind: 'default', value: 'none' },
        shape: { kind: 'default', value: 'plain' },
        skeletonRowCount: { kind: 'default', value: 6 },
        sortMode: { kind: 'default', value: 'client' },
        treeSelectionBehavior: { kind: 'default', value: 'cascade' },
        virtualizeThreshold: { kind: 'default', value: 50 },
      },
    },
    Layout: {
      props: {
        contentPadding: { kind: 'default', value: '1x' },
        display: { kind: 'default', value: 'flex' },
        doNotOverflow: { kind: 'default', value: false },
        flexGrow: { kind: 'default', value: 1 },
        flow: { kind: 'default', value: 'column' },
        hasTransition: { kind: 'default', value: false },
        minContentSize: { kind: 'default', value: 320 },
        placeSelf: { kind: 'default', value: 'stretch' },
        position: {
          kind: 'skip',
          reason: 'unverified',
          note: 'Rendering <Layout position={"absolute"}> differs from omitting it, so the documented default could not be reproduced. Check for docs drift, an alias mapping, or a state-map style default. Docs say `absolute`.',
        },
      },
    },
    ListBox: {
      props: {
        disableSelectionToggle: { kind: 'default', value: false },
        disallowEmptySelection: { kind: 'default', value: false },
        focusOnHover: { kind: 'default', value: true },
        isCheckable: { kind: 'default', value: false },
        isReorderable: { kind: 'default', value: false },
        selectionMode: { kind: 'default', value: 'single' },
        shape: { kind: 'default', value: 'card' },
        shouldFocusWrap: { kind: 'default', value: false },
        shouldUseVirtualFocus: { kind: 'default', value: false },
        showSelectAll: { kind: 'default', value: false },
        size: { kind: 'default', value: 'medium' },
      },
    },
    LoadingAnimation: {
      props: {
        size: { kind: 'default', value: 'medium' },
      },
    },
    Menu: {
      props: {
        autoFocus: { kind: 'default', value: false },
        selectionMode: { kind: 'default', value: 'none' },
        shouldFocusWrap: { kind: 'default', value: false },
        size: { kind: 'default', value: 'medium' },
      },
    },
    MenuTrigger: {
      props: {
        crossOffset: { kind: 'default', value: 0 },
        mobileType: { kind: 'default', value: 'popover' },
        offset: { kind: 'default', value: 8 },
        placement: { kind: 'default', value: 'bottom start' },
        shouldFlip: { kind: 'default', value: true },
        shouldRestoreFocus: { kind: 'default', value: true },
        trigger: { kind: 'default', value: 'press' },
      },
    },
    NumberInput: {
      props: {
        hideStepper: { kind: 'default', value: false },
        size: { kind: 'default', value: 'medium' },
        suffixPosition: { kind: 'default', value: 'before' },
      },
    },
    Pagination: {
      props: {
        boundaryCount: { kind: 'default', value: 1 },
        defaultPage: { kind: 'default', value: 1 },
        defaultPageSize: { kind: 'default', value: 50 },
        isCompact: { kind: 'default', value: false },
        siblingCount: { kind: 'default', value: 1 },
        size: { kind: 'default', value: 'small' },
        type: { kind: 'default', value: 'numbers' },
      },
    },
    PasswordInput: {
      props: {
        isBuffered: { kind: 'default', value: true },
        size: { kind: 'default', value: 'medium' },
        suffixPosition: { kind: 'default', value: 'after' },
      },
    },
    Picker: {
      props: {
        disallowEmptySelection: { kind: 'default', value: false },
        isCheckable: { kind: 'default', value: false },
        isClearable: { kind: 'default', value: false },
        selectionMode: { kind: 'default', value: 'single' },
        showSelectAll: { kind: 'default', value: false },
        size: { kind: 'default', value: 'medium' },
        theme: { kind: 'default', value: 'default' },
        type: { kind: 'default', value: 'outline' },
      },
    },
    Placeholder: {
      props: {
        display: { kind: 'default', value: 'block' },
        height: { kind: 'default', value: '2x' },
        size: { kind: 'default', value: '2x' },
      },
    },
    Portal: {
      props: {
        isDisabled: { kind: 'default', value: false },
      },
    },
    Prefix: {
      props: {
        display: { kind: 'default', value: 'grid' },
        flow: { kind: 'default', value: 'column' },
        gap: { kind: 'default', value: 0 },
        outerGap: { kind: 'default', value: '1bw' },
        placeItems: { kind: 'default', value: 'center' },
        position: { kind: 'default', value: 'absolute' },
      },
    },
    PrismCode: {
      props: {
        margin: { kind: 'default', value: 0 },
        overflow: { kind: 'default', value: 'auto' },
        padding: { kind: 'default', value: 0 },
        scrollbar: { kind: 'default', value: 'styled' },
      },
    },
    RadioGroup: {
      props: {
        size: { kind: 'default', value: 'medium' },
        type: { kind: 'default', value: 'radio' },
      },
    },
    ResizablePanel: {
      props: {
        direction: { kind: 'default', value: 'right' },
        maxSize: { kind: 'default', value: 'min(50%, 400px)' },
        minSize: { kind: 'default', value: 200 },
      },
    },
    Result: {
      props: {
        flow: { kind: 'default', value: 'column' },
        isCompact: { kind: 'default', value: false },
        status: { kind: 'default', value: 'info' },
      },
    },
    SearchComboBox: {
      props: {
        containerPadding: { kind: 'default', value: 8 },
        direction: { kind: 'default', value: 'bottom' },
        hideTrigger: { kind: 'default', value: true },
        isClearable: { kind: 'default', value: true },
        isLoading: { kind: 'default', value: false },
        loadingDelay: { kind: 'default', value: 1000 },
        overlayOffset: { kind: 'default', value: 8 },
        popoverTrigger: { kind: 'default', value: 'input' },
        shouldFlip: { kind: 'default', value: true },
        size: { kind: 'default', value: 'medium' },
        suffixPosition: { kind: 'default', value: 'before' },
      },
    },
    SearchInput: {
      props: {
        isBuffered: { kind: 'default', value: true },
        isClearable: { kind: 'default', value: false },
        size: { kind: 'default', value: 'medium' },
        suffixPosition: { kind: 'default', value: 'after' },
      },
    },
    Select: {
      props: {
        containerPadding: { kind: 'default', value: 8 },
        direction: { kind: 'default', value: 'bottom' },
        hideTrigger: { kind: 'default', value: false },
        isClearable: { kind: 'default', value: false },
        overlayOffset: { kind: 'default', value: 8 },
        shape: { kind: 'default', value: 'button' },
        shouldFlip: { kind: 'default', value: true },
        size: { kind: 'default', value: 'medium' },
        suffixPosition: { kind: 'default', value: 'before' },
        theme: { kind: 'default', value: 'default' },
        type: { kind: 'default', value: 'outline' },
      },
    },
    Skeleton: {
      props: {
        cards: { kind: 'default', value: 3 },
        columns: { kind: 'default', value: 5 },
        isStatic: { kind: 'default', value: false },
        layout: { kind: 'default', value: 'page' },
        lines: { kind: 'default', value: 5 },
        rows: { kind: 'default', value: 5 },
        size: { kind: 'default', value: '2x' },
        tabs: { kind: 'default', value: 3 },
      },
    },
    Slider: {
      props: {
        maxValue: { kind: 'default', value: 100 },
        minValue: { kind: 'default', value: 0 },
        orientation: { kind: 'default', value: 'horizontal' },
        step: { kind: 'default', value: 1 },
      },
    },
    Space: {
      props: {
        direction: { kind: 'default', value: 'horizontal' },
        display: { kind: 'default', value: 'flex' },
        gap: { kind: 'default', value: '1x' },
      },
    },
    Spin: {
      props: {
        size: { kind: 'default', value: 'default' },
        spinning: { kind: 'default', value: true },
      },
    },
    Suffix: {
      props: {
        display: { kind: 'default', value: 'grid' },
        flow: { kind: 'default', value: 'column' },
        gap: { kind: 'default', value: 0 },
        outerGap: { kind: 'default', value: '1bw' },
        placeItems: { kind: 'default', value: 'center' },
        position: { kind: 'default', value: 'absolute' },
      },
    },
    Switch: {
      props: {
        defaultSelected: { kind: 'default', value: false },
        isSelected: { kind: 'default', value: false },
        size: { kind: 'default', value: 'medium' },
      },
    },
    Tabs: {
      props: {
        contextMenu: { kind: 'default', value: false },
        hideTabListScroll: { kind: 'default', value: false },
        isEditable: { kind: 'default', value: false },
        isReorderable: { kind: 'default', value: false },
        keepMounted: { kind: 'default', value: false },
        label: { kind: 'default', value: 'Tabs' },
        placement: { kind: 'default', value: 'top' },
        prerender: { kind: 'default', value: false },
        scrollArrowsPosition: { kind: 'default', value: 'suffix' },
        showScrollArrows: { kind: 'default', value: false },
        showTabPicker: { kind: 'default', value: false },
        size: {
          kind: 'skip',
          reason: 'reflected-attribute',
          note: "Default is 'medium', but Tabs renders `data-size={size}`, so omitting the prop drops the attribute while 'medium' emits it. Not lintable.",
        },
        tabPickerPosition: { kind: 'default', value: 'suffix' },
        type: { kind: 'default', value: 'default' },
      },
    },
    Tag: {
      props: {
        autoHideActions: { kind: 'default', value: false },
        disableActionsFocus: { kind: 'default', value: false },
        highlightCaseSensitive: { kind: 'default', value: false },
        isClosable: { kind: 'default', value: false },
        isLoading: { kind: 'default', value: false },
        isSelected: {
          kind: 'skip',
          reason: 'reflected-attribute',
          note: 'Reflected as `aria-selected={isSelected}`, so omitting the prop removes the attribute while `false` emits `aria-selected="false"`. Not safe to strip.',
        },
        level: { kind: 'default', value: 3 },
        preserveActionsSpace: { kind: 'default', value: false },
        size: { kind: 'default', value: 'inline' },
        theme: { kind: 'default', value: 'default' },
        tooltip: { kind: 'default', value: true },
      },
    },
    Text: {
      props: {
        as: { kind: 'default', value: 'span' },
        margin: { kind: 'default', value: 0 },
        padding: { kind: 'default', value: 0 },
      },
    },
    TextArea: {
      props: {
        autoSize: { kind: 'default', value: false },
        isBuffered: { kind: 'default', value: true },
        maxRows: { kind: 'default', value: 10 },
        rows: { kind: 'default', value: 3 },
        size: { kind: 'default', value: 'medium' },
        suffixPosition: { kind: 'default', value: 'before' },
      },
    },
    TextInput: {
      props: {
        isBuffered: { kind: 'default', value: true },
        multiLine: { kind: 'default', value: false },
        size: { kind: 'default', value: 'medium' },
        suffixPosition: { kind: 'default', value: 'before' },
        type: { kind: 'default', value: 'text' },
      },
    },
    TextInputMapper: {
      props: {
        actionLabel: { kind: 'default', value: 'Mapping' },
        size: { kind: 'default', value: 'medium' },
      },
    },
    TextItem: {
      props: {
        highlightCaseSensitive: { kind: 'default', value: false },
        tooltip: { kind: 'default', value: true },
        tooltipPlacement: { kind: 'default', value: 'top' },
      },
    },
    Title: {
      props: {
        display: { kind: 'default', value: 'block' },
        gridArea: { kind: 'default', value: 'title' },
        level: { kind: 'default', value: 1 },
        margin: { kind: 'default', value: 0 },
      },
    },
    Tooltip: {
      props: {
        placement: { kind: 'default', value: 'top' },
      },
    },
    TooltipProvider: {
      props: {
        closeDelay: { kind: 'default', value: 500 },
        crossOffset: { kind: 'default', value: 0 },
        delay: { kind: 'default', value: 250 },
        offset: { kind: 'default', value: 8 },
        placement: { kind: 'default', value: 'top' },
        shouldCloseOnPress: { kind: 'default', value: true },
      },
    },
    TooltipTrigger: {
      props: {
        closeDelay: { kind: 'default', value: 500 },
        crossOffset: { kind: 'default', value: 0 },
        delay: { kind: 'default', value: 250 },
        offset: { kind: 'default', value: 8 },
        placement: { kind: 'default', value: 'top' },
        shouldCloseOnPress: { kind: 'default', value: true },
      },
    },
    Tree: {
      props: {
        autoExpandParent: { kind: 'default', value: false },
        contextMenu: { kind: 'default', value: false },
        isCheckable: { kind: 'default', value: false },
        isDisabled: { kind: 'default', value: false },
        selectionMode: { kind: 'default', value: 'single' },
      },
    },
  },
  // Export paths that are the same object as the component
  // above them — `Radio.Group` *is* `RadioGroup`.
  aliases: {
    'Button.Split': 'ButtonSplit',
    'CollectionItem.Action': 'ItemAction',
    'CollectionItem.Badge': 'ItemBadge',
    'CommandMenu.Trigger': 'MenuTrigger',
    Input: 'TextInput',
    'Input.File': 'FileInput',
    'Input.Number': 'NumberInput',
    'Input.Password': 'PasswordInput',
    'Input.Text': 'TextInput',
    'Input.TextArea': 'TextArea',
    'Item.Action': 'ItemAction',
    'Item.Badge': 'ItemBadge',
    ItemBase: 'Item',
    'ItemBase.Action': 'ItemAction',
    'ItemBase.Badge': 'ItemBadge',
    'ItemButton.Action': 'ItemAction',
    'ItemButton.Badge': 'ItemBadge',
    'ItemCard.Action': 'ItemAction',
    'Menu.Trigger': 'MenuTrigger',
    'Radio.Group': 'RadioGroup',
    'TextInput.File': 'FileInput',
    'TextInput.Number': 'NumberInput',
    'TextInput.Password': 'PasswordInput',
    'TextInput.Text': 'TextInput',
    'TextInput.TextArea': 'TextArea',
    'Typography.Text': 'Text',
    'Typography.Title': 'Title',
  },
};
