import * as UIKit from '../index';

import { readDocumentedDefaults } from './docs-defaults';
import { FIXTURES } from './fixtures';
import { classifyProp, Fixture } from './probe';
import { ComponentEntry, DefaultsRegistry, PropEntry } from './types';

/**
 * Pregenerate the registry by proving every documented default against the
 * running component.
 *
 * The output is deliberately reviewable: `default` entries are what the lint
 * rule acts on, and every exclusion carries a machine-written reason so a
 * reviewer (or an AI keeping the registry in sync) can tell a proven skip from
 * an untriaged one.
 */

export function buildComponentEntry(fixture: Fixture): ComponentEntry {
  const documented = readDocumentedDefaults(fixture.name);
  const ignore = new Set(fixture.ignoreProps ?? []);
  const props: Record<string, PropEntry> = {};

  for (const { prop, raw, value } of documented) {
    if (ignore.has(prop)) continue;

    const curated = fixture.curatedSkips?.[prop];

    if (curated) {
      props[prop] = { kind: 'skip', ...curated };
      continue;
    }

    if (value === undefined) {
      // Not a plain literal (`undefined`, `[]`, `() => {}`, prose). A JSX
      // attribute can never be compared against it, so it is out of scope
      // rather than unverified.
      continue;
    }

    const entry = classifyProp(fixture, prop, value);

    if (entry.kind === 'default') {
      // Hand-curated only — aliases cannot be safely inferred from rendering.
      const aliases = fixture.curatedAliases?.[prop]?.filter(
        (alias) => alias !== value,
      );

      props[prop] = aliases?.length ? { ...entry, aliases } : entry;
      continue;
    }

    props[prop] =
      entry.reason === 'unverified'
        ? // Preserve what the docs claimed, so drift is actionable.
          { ...entry, note: `${entry.note} Docs say \`${raw}\`.` }
        : entry;
  }

  return { props };
}

/** A module namespace or a component object hanging compound aliases off itself. */
type Namespace = Record<string, unknown>;

function resolveExport(namespace: Namespace, path: string): unknown {
  return path
    .split('.')
    .reduce<unknown>(
      (target, part) => (target as Namespace)?.[part],
      namespace as unknown,
    );
}

/**
 * Find every *other* export path that resolves to the same object as a covered
 * component, so the rule catches `<Radio.Group>` as well as `<RadioGroup>`.
 *
 * The test is object identity, deliberately — not the name. `Radio.Group` is
 * `RadioGroup` itself, so it cannot behave differently and inherits the entry
 * safely; `Radio.ButtonGroup` is `tasty(RadioGroup, { type: 'button' })`, a
 * *different* object whose effective `type` default is not RadioGroup's, so it
 * is skipped. A name-shape heuristic (`Radio` + `ButtonGroup` -> `RadioButtonGroup`,
 * `Radio.Group` -> `RadioGroup`) cannot tell those two apart; identity cannot get
 * it wrong.
 *
 * Only one level of nesting is scanned, which is all ui-kit uses.
 */
export function findAliases(
  names: string[],
  namespace: Namespace = UIKit as unknown as Namespace,
): Record<string, string> {
  const canonical = new Map<unknown, string>();

  for (const name of names) {
    const component = resolveExport(namespace, name);

    // First fixture wins, so the output stays stable if two fixtures ever name
    // the same object.
    if (component && !canonical.has(component)) canonical.set(component, name);
  }

  const aliases: Record<string, string> = {};

  const record = (path: string, target: string | undefined) => {
    if (target && target !== path) aliases[path] = target;
  };

  for (const [name, exported] of Object.entries(namespace)) {
    if (
      !exported ||
      (typeof exported !== 'function' && typeof exported !== 'object')
    ) {
      continue;
    }

    // A second flat export of the same object: `Input` *is* `TextInput`
    // (`Object.assign` mutates and returns it), `ItemBase` *is* `Item`.
    record(name, canonical.get(exported));

    for (const [key, nested] of Object.entries(exported as Namespace)) {
      record(`${name}.${key}`, canonical.get(nested));
    }
  }

  return Object.fromEntries(
    Object.keys(aliases)
      .sort()
      .map((alias) => [alias, aliases[alias]]),
  );
}

export function buildRegistry(
  fixtures: Fixture[] = FIXTURES,
): DefaultsRegistry {
  const components: Record<string, ComponentEntry> = {};

  for (const fixture of fixtures) {
    components[fixture.name] = buildComponentEntry(fixture);
  }

  return {
    components,
    aliases: findAliases(fixtures.map((fixture) => fixture.name)),
  };
}

/** Render the registry as the source of `defaults.generated.ts`. */
export function serializeRegistry(registry: DefaultsRegistry): string {
  const names = Object.keys(registry.components).sort();
  const lines: string[] = [
    '/* eslint-disable */',
    '// AUTOGENERATED by `pnpm audit-defaults`. Do not edit by hand.',
    '//',
    '// Each entry was proven by rendering the component twice — once with the',
    '// prop, once without — and comparing markup and tasty CSS. See',
    '// `src/eslint-plugin/probe.tsx`.',
    '',
    "import { DefaultsRegistry } from './types';",
    '',
    'export const DEFAULTS: DefaultsRegistry = {',
    '  components: {',
  ];

  for (const name of names) {
    const entry = registry.components[name];
    const props = Object.keys(entry.props).sort();

    lines.push(`    ${JSON.stringify(name)}: {`);
    lines.push('      props: {');

    for (const prop of props) {
      const value = entry.props[prop];

      if (value.kind === 'default') {
        const aliases = value.aliases?.length
          ? `, aliases: ${JSON.stringify(value.aliases)}`
          : '';

        lines.push(
          `        ${JSON.stringify(prop)}: { kind: 'default', value: ${JSON.stringify(value.value)}${aliases} },`,
        );
      } else {
        lines.push(`        ${JSON.stringify(prop)}: {`);
        lines.push(`          kind: 'skip',`);
        lines.push(`          reason: ${JSON.stringify(value.reason)},`);
        lines.push(`          note: ${JSON.stringify(value.note)},`);
        lines.push('        },');
      }
    }

    lines.push('      },');
    lines.push('    },');
  }

  lines.push('  },');

  const aliases = registry.aliases ?? {};
  const aliasNames = Object.keys(aliases).sort();

  if (aliasNames.length) {
    lines.push('  // Export paths that are the same object as the component');
    lines.push('  // above them — `Radio.Group` *is* `RadioGroup`.');
    lines.push('  aliases: {');

    for (const alias of aliasNames) {
      lines.push(
        `    ${JSON.stringify(alias)}: ${JSON.stringify(aliases[alias])},`,
      );
    }

    lines.push('  },');
  }

  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

/** Compact shape for comparing a fresh run against the committed registry. */
export function summarize(registry: DefaultsRegistry): Record<string, string> {
  const out: Record<string, string> = {};

  for (const [name, entry] of Object.entries(registry.components)) {
    for (const [prop, value] of Object.entries(entry.props)) {
      out[`${name}.${prop}`] =
        value.kind === 'default'
          ? // Aliases are part of what the rule acts on, so a change in them has
            // to fail the sync guard too.
            `default:${JSON.stringify(value.value)}${
              value.aliases?.length
                ? `+${JSON.stringify([...value.aliases].sort())}`
                : ''
            }`
          : `skip:${value.reason}`;
    }
  }

  // An alias that appears or disappears changes what the rule reports just as
  // much as a moved default, so the sync guard has to see it too.
  for (const [alias, target] of Object.entries(registry.aliases ?? {})) {
    out[`alias:${alias}`] = target;
  }

  return out;
}
