import { readDocumentedDefaults } from './docs-defaults';
import { FIXTURES } from './fixtures';
import { classifyProp, Fixture } from './probe';
import { ComponentEntry, DefaultsRegistry, PropEntry } from './types';

/**
 * Pregenerate the registry by proving every documented default against the
 * running component.
 *
 * The output is deliberately reviewable: `default` entries are what the lint
 * rule acts on, and every exclusion carries a machine-written reason so a
 * reviewer (or an AI keeping the registry in sync) can tell a proven skip from
 * an untriaged one.
 */

export function buildComponentEntry(fixture: Fixture): ComponentEntry {
  const documented = readDocumentedDefaults(fixture.name);
  const ignore = new Set(fixture.ignoreProps ?? []);
  const props: Record<string, PropEntry> = {};

  for (const { prop, raw, value } of documented) {
    if (ignore.has(prop)) continue;

    const curated = fixture.curatedSkips?.[prop];

    if (curated) {
      props[prop] = { kind: 'skip', ...curated };
      continue;
    }

    if (value === undefined) {
      // Not a plain literal (`undefined`, `[]`, `() => {}`, prose). A JSX
      // attribute can never be compared against it, so it is out of scope
      // rather than unverified.
      continue;
    }

    const entry = classifyProp(fixture, prop, value);

    if (entry.kind === 'default') {
      // Hand-curated only — aliases cannot be safely inferred from rendering.
      const aliases = fixture.curatedAliases?.[prop]?.filter(
        (alias) => alias !== value,
      );

      props[prop] = aliases?.length ? { ...entry, aliases } : entry;
      continue;
    }

    props[prop] =
      entry.reason === 'unverified'
        ? // Preserve what the docs claimed, so drift is actionable.
          { ...entry, note: `${entry.note} Docs say \`${raw}\`.` }
        : entry;
  }

  return { props };
}

export function buildRegistry(
  fixtures: Fixture[] = FIXTURES,
): DefaultsRegistry {
  const components: Record<string, ComponentEntry> = {};

  for (const fixture of fixtures) {
    components[fixture.name] = buildComponentEntry(fixture);
  }

  return { components };
}

/** Render the registry as the source of `defaults.generated.ts`. */
export function serializeRegistry(registry: DefaultsRegistry): string {
  const names = Object.keys(registry.components).sort();
  const lines: string[] = [
    '/* eslint-disable */',
    '// AUTOGENERATED by `pnpm audit-defaults`. Do not edit by hand.',
    '//',
    '// Each entry was proven by rendering the component twice — once with the',
    '// prop, once without — and comparing markup and tasty CSS. See',
    '// `src/eslint-plugin/probe.tsx`.',
    '',
    "import { DefaultsRegistry } from './types';",
    '',
    'export const DEFAULTS: DefaultsRegistry = {',
    '  components: {',
  ];

  for (const name of names) {
    const entry = registry.components[name];
    const props = Object.keys(entry.props).sort();

    lines.push(`    ${JSON.stringify(name)}: {`);
    lines.push('      props: {');

    for (const prop of props) {
      const value = entry.props[prop];

      if (value.kind === 'default') {
        const aliases = value.aliases?.length
          ? `, aliases: ${JSON.stringify(value.aliases)}`
          : '';

        lines.push(
          `        ${JSON.stringify(prop)}: { kind: 'default', value: ${JSON.stringify(value.value)}${aliases} },`,
        );
      } else {
        lines.push(`        ${JSON.stringify(prop)}: {`);
        lines.push(`          kind: 'skip',`);
        lines.push(`          reason: ${JSON.stringify(value.reason)},`);
        lines.push(`          note: ${JSON.stringify(value.note)},`);
        lines.push('        },');
      }
    }

    lines.push('      },');
    lines.push('    },');
  }

  lines.push('  },');
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

/** Compact shape for comparing a fresh run against the committed registry. */
export function summarize(registry: DefaultsRegistry): Record<string, string> {
  const out: Record<string, string> = {};

  for (const [name, entry] of Object.entries(registry.components)) {
    for (const [prop, value] of Object.entries(entry.props)) {
      out[`${name}.${prop}`] =
        value.kind === 'default'
          ? // Aliases are part of what the rule acts on, so a change in them has
            // to fail the sync guard too.
            `default:${JSON.stringify(value.value)}${
              value.aliases?.length
                ? `+${JSON.stringify([...value.aliases].sort())}`
                : ''
            }`
          : `skip:${value.reason}`;
    }
  }

  return out;
}
