/**
 * Schema for the redundant-default-prop registry.
 *
 * Entries are pregenerated by the differential-render prover
 * (`pnpm audit-defaults`) and reviewed by hand. The lint rule only ever reports
 * `VerifiedDefault` entries — every other classification is an explicit
 * exclusion, recorded rather than omitted so the prover can assert the registry
 * is *complete* and a newly added prop fails until it has been triaged.
 */

/** A literal prop value the rule can compare a JSX attribute against. */
export type DefaultValue = string | number | boolean;

/**
 * Why a prop is excluded from the rule. Recorded explicitly so a reviewer can
 * tell "we proved this is unsafe" from "nobody has looked at it yet".
 */
export type SkipReason =
  /** Default depends on another prop of the same component (e.g. Button `size` depends on `type === 'link'`). */
  | 'conditional'
  /** Default comes from React context, so it is load-bearing under a provider (e.g. ItemAction `theme`). */
  | 'context'
  /**
   * The prop's default lives in a tasty state map, not a scalar. Passing even
   * the default-state value replaces the whole map and drops its other
   * branches, so it is a real behaviour change. Button `radius` is
   * `{ '': true, '@parent(button-split, >) & !:last-child': '1r left', ... }`.
   */
  | 'state-map'
  /**
   * The prop is reflected straight onto the DOM as a `data-*` / `aria-*`
   * attribute, so omitting it drops the attribute while passing its documented
   * default emits it. The values are equal but the rendered output is not, and
   * for `aria-*` that difference is meaningful to assistive tech — removing it
   * would be a real change. `Tabs` renders `data-size={size}`; `Item` renders
   * `aria-selected={isSelected}`.
   */
  | 'reflected-attribute'
  /** The documented default could not be reproduced by rendering — docs may have drifted. Needs a human. */
  | 'unverified'
  /** No render fixture exists for this component yet, so nothing could be proven. */
  | 'no-fixture';

export interface VerifiedDefault {
  kind: 'default';
  /** The value that is redundant to pass explicitly. */
  value: DefaultValue;
  /**
   * Extra literals that normalise to the same default, so aliases are caught
   * too. Dialog declares `size = 'M'` but maps `M -> medium`, making both
   * `<Dialog size="M">` and `<Dialog size="medium">` redundant.
   */
  aliases?: DefaultValue[];
}

export interface SkippedProp {
  kind: 'skip';
  reason: SkipReason;
  /** Human-readable justification. Required — an unexplained skip is indistinguishable from a bug. */
  note: string;
}

export type PropEntry = VerifiedDefault | SkippedProp;

export interface ComponentEntry {
  /** Keyed by prop name. */
  props: Record<string, PropEntry>;
}

export interface DefaultsRegistry {
  /**
   * Keyed by the name the component is *exported* under from
   * `@cube-dev/ui-kit` — the name its render fixture carries. The lint rule
   * resolves a JSX tag back to this name via its import binding, so a local
   * component that merely shares a name is never matched.
   */
  components: Record<string, ComponentEntry>;
  /**
   * Other export paths that are *literally the same component object* as a
   * `components` key, mapped alias -> canonical key.
   *
   * ui-kit hangs compound aliases off its components — `Radio.Group` is the
   * `RadioGroup` export, `Button.Split` is `ButtonSplit`, `Input` is
   * `TextInput`. The dotted form is usually the idiomatic one, so without this
   * the entry is close to dead: the rule resolves `<Radio.Group>` to the dotted
   * path, misses the flat key, and stays silent.
   *
   * Derived by object identity, never by name shape — see `findAliases` in
   * `generate.ts`. `Radio.ButtonGroup` is `tasty(RadioGroup, { type: 'button' })`
   * and `Radio.Tabs` is `tasty(RadioGroup, { type: 'tabs' })`: different objects
   * with a different effective `type` default, so neither is an alias.
   *
   * Unrelated to `VerifiedDefault.aliases`, which lists alternate spellings of a
   * prop *value*.
   */
  aliases?: Record<string, string>;
}

export function isVerified(entry: PropEntry): entry is VerifiedDefault {
  return entry.kind === 'default';
}
