/**
 * cleanup-docs.mjs
 *
 * Removes files generated by prepare-docs.mjs using the manifest,
 * and restores the docs/tasty symlink if it was replaced with a copy.
 */

import fs from 'node:fs/promises';
import path from 'node:path';

const DOCS_DIR = 'docs';
const MANIFEST = '.docs-generated';
const TASTY_PATH = path.join(DOCS_DIR, 'tasty');
const TASTY_SYMLINK_TARGET = path.join('..', 'node_modules', '@tenphi', 'tasty', 'docs');

try {
  const content = await fs.readFile(MANIFEST, 'utf8');
  const files = content.trim().split('\n').filter(Boolean);

  for (const file of files) {
    await fs.rm(file, { force: true });
  }

  await fs.rm(path.join(DOCS_DIR, 'components'), {
    recursive: true,
    force: true,
  });
  await fs.rm(MANIFEST, { force: true });

  console.log(`[cleanup-docs] Removed ${files.length} generated files`);
} catch {
  // No manifest means nothing to clean
}

// Restore tasty symlink
await fs.rm(TASTY_PATH, { recursive: true, force: true });
await fs.symlink(TASTY_SYMLINK_TARGET, TASTY_PATH);
console.log('[cleanup-docs] Restored tasty symlink');
