/**
 * cleanup-docs.mjs
 *
 * Removes files generated by prepare-docs.mjs using the manifest,
 * and restores the docs/tasty and docs/glaze symlinks if they were
 * replaced with copies during pack.
 */

import fs from 'node:fs/promises';
import path from 'node:path';

const DOCS_DIR = 'docs';
const MANIFEST = '.docs-generated';

const VENDORED_SYMLINKS = [
  {
    name: 'tasty',
    target: path.join('..', 'node_modules', '@tenphi', 'tasty', 'docs'),
  },
  {
    name: 'glaze',
    target: path.join('..', 'node_modules', '@tenphi', 'glaze', 'docs'),
  },
];

try {
  const content = await fs.readFile(MANIFEST, 'utf8');
  const files = content.trim().split('\n').filter(Boolean);

  for (const file of files) {
    await fs.rm(file, { force: true });
  }

  await fs.rm(path.join(DOCS_DIR, 'components'), {
    recursive: true,
    force: true,
  });
  await fs.rm(MANIFEST, { force: true });

  console.log(`[cleanup-docs] Removed ${files.length} generated files`);
} catch {
  // No manifest means nothing to clean
}

for (const { name, target } of VENDORED_SYMLINKS) {
  const linkPath = path.join(DOCS_DIR, name);
  await fs.rm(linkPath, { recursive: true, force: true });
  await fs.symlink(target, linkPath);
  console.log(`[cleanup-docs] Restored ${name} symlink`);
}
