import type { Styles } from '@tenphi/tasty';

/**
 * Shadow tokens using tasty shorthand syntax.
 *
 * Format: `<offset-y> <blur> <spread?> <color>`
 * - `1bw` = 1 × border-width
 * - `.5x` = 0.5 × gap
 *
 * The shadow colors (`#shadow-sm` / `#shadow-md` / `#shadow-lg`) are
 * generated by Glaze and adapt automatically to dark / high-contrast
 * schemes — see `src/tokens/palette.ts`.
 *
 * Keys use $ prefix for CSS custom properties.
 */
export const SHADOW_TOKENS: Styles = {
  /** Subtle shadow for list items */
  '$item-shadow': '0 1bw .375x #shadow-sm',
  /** Standard card shadow */
  '$card-shadow': '0 .5x 2x #shadow-md',
  /** Standard elevation */
  $shadow: '0 .5x 2x #shadow-md',
  /** Elevated dialog shadow */
  '$dialog-shadow': '0 1x 4x #shadow-lg',
};
